name: asciidoctor-ghpages
on:
  push:
    paths:
      - 'docs/**'
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Load Docker
      uses: docker://asciidoctor/docker-asciidoctor
      with:
        args: -it -v docs
    - name: Generate HTML
      run: asciidoctor -r asciidoctor-bibtex docs/manual.adoc