name: asciidoctor-ghpages
on:
  push:
    paths:
      - 'docs/**'
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Generate HTML
      uses: docker://asciidoctor/docker-asciidoctor
      with:
        entrypoint: asciidoctor
        args: -r asciidoctor-bibtex docs/manual.adoc
    - name: Generate PDF
      uses: docker://asciidoctor/docker-asciidoctor
      with:
        entrypoint: asciidoctor-pdf
        args: -r asciidoctor-bibtex -r asciidoctor-mathematical -a mathematical-format=svg -a optimize -a pdf-theme=docs/resources/themes/manual.yml -a pdf-fontsdir=docs/resources/fonts